new Mdlint

diff --git a/.github/workflows/markdown_lint.yml b/.github/workflows/markdown_lint.yml
--- a/.github/workflows/markdown_lint.yml
+++ b/.github/workflows/markdown_lint.yml
@@ -3,10 +3,12 @@ name: Markdown Lint
 on:
   push:
     branches:
-      - '*'
+      - main
   pull_request:
     branches:
-      - '*'
+      - main
+    paths:
+      - '**/*.md' # Only run on Markdown file changes
 
 jobs:
   markdown-lint:
@@ -16,16 +18,46 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
+      - name: Install zhlint
+        run: yarn global add zhlint
+
+      - name: Get changed Markdown files
+        id: changed-files
+        uses: tj-actions/changed-files@v45
         with:
-          node-version: '20'  
+          files: '**/*.md'
 
-      - name: Verify Node.js version
-        run: node -v 
+      - name: Lint Markdown files
+        env:
+          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
+          mkdir -p linted_output
+          file_list="linted_output/file_list.txt"
+          linted_failed=0
+          for file in ${{ env.ALL_CHANGED_FILES }}; do
+            set +e
+            zhlint --config "$GITHUB_WORKSPACE"/ci/.zhlintrc "$file"
+            if [ $? -ne 0 ]; then
+              linted_failed=1
+              echo "$file" >> "$file_list"
+              output_file="linted_output/report_and_suggested_fixes/$file"
+              mkdir -p "$(dirname "$output_file")"
+              zhlint --config "$GITHUB_WORKSPACE"/ci/.zhlintrc "$file" --output="$output_file" > "$output_file.log" 2>&1
+            fi
+            set -e
+          done
+          echo "linted_failed=$linted_failed" >> "$GITHUB_ENV"
 
-      - name: Install markdownlint-cli
-        run: npm install -g markdownlint-cli@latest
+      - name: Upload Linted Markdown
+        uses: actions/upload-artifact@v4
+        with:
+          name: linted-markdown
+          path: linted_output/
 
-      - name: Run Markdown Lint
-        run: npx markdownlint-cli **/*.md
+      - name: Check lint errors
+        run: |
+          set -e
+          if [ "${{ env.linted_failed }}" -ne 0 ]; then
+            echo "Linting errors found. Please check the reports and suggested fixes in uploaded artifact."
+            exit 1
+          fi
